project:
  type: website
  output-dir: docs

# Meta
description-meta: "Course on Food and Agricultural Markets"
author-meta: "Lauren Chenarides"

website:
  title: "Food & Ag Markets"
  description: "Course on Food and Agricultural Markets"
  navbar:
    background: light
    left:
      - text: Market Analysis Project
        href: project/project-instructions.qmd
      - text: "Spring 2026"
        menu:
          - text: Syllabus
            href: 2026sp/syllabus.qmd
          - text: Schedule
            href: 2026sp/schedule.qmd
          - text: Readings
            href: 2026sp/readings.qmd
      - text: "Fall 2025"
        menu:
          - text: Syllabus - Fall 2025
            href: syllabus.qmd
          - text: Schedule - Fall 2025
            href: 2025/schedule.qmd
          - text: Readings
            href: 2025/readings.qmd
          - text: "Market Data Analysis Project"
            href: 2025/project-instructions.qmd
          - text: "Excel Lab (In-Class)"
            href: 2025/excel-lab.qmd
          - text: "Assignment 2 (Excel Primer)"
            href: 2025/excel-course.qmd
          - text: "Assignment 3"
            href: 2025/hw3.qmd
          - text: "Assignment 4"
            href: 2025/hw4.qmd
          - text: "Assignment 4 - Solution Key"
            href: 2025/hw4-solution.qmd
          - text: "Assignment 5"
            href: 2025/hw5.qmd
          - text: "Assignment 5 - Solution Key"
            href: 2025/hw5-solution.qmd
          - text: "Equilibrium Displacement Models"
            href: 2025/edm.qmd
          - text: "Multi-Sector Model"
            href: 2025/multi_sector_model.qmd
          - text: "SSNIP Test for Market Definition"
            href: 2025/ssnip.qmd

    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-310
  page-navigation: true
  page-footer: 
    left: "[Lauren Chenarides](https://github.com/laurenchenarides/csu-arec-310) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-310
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/laurenchenarides/csu-arec-310
  repo-actions: [edit, issue, source]
  open-graph: true
  site-url: "https://github.com/laurenchenarides/csu-arec-310"
  google-analytics:
    tracking-id: "G-GG4GM3TPXK"
    anonymize-ip: false

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true

execute: 
  freeze: auto

comments:
  hypothesis: false
  

