project:
  type: website
  output-dir: docs

# Meta
description-meta: "Course on Food and Agricultural Markets developed by Dr. Lauren Chenarides."
author-meta: "Lauren Chenarides"

website:
  title: "Food & Ag Markets"
  description: "Course on Food and Agricultural Markets developed by Dr. Lauren Chenarides"
  navbar:
    background: light
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: 2025/schedule.qmd
      - text: Marketing Project
        href: project/project-instructions.qmd                
      - text: Readings
        href: 2025/readings.qmd
      # - text: Lectures
      #   href: lectures/lectures.qmd
      # - text: Archive
      #   menu:
      #     - text: Fall 2025
      #       href: 2025/schedule.qmd         
      # - text: Dr. Lauren Chenarides
      #   href: https://scholar.google.com/citations?user=07RAgEQAAAAJ&hl=en
      #   target: _blank        
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-310
  page-navigation: true
  page-footer: 
    left: "[Lauren Chenarides](https://github.com/laurenchenarides/csu-arec-310) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-310
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/laurenchenarides/csu-arec-310
  repo-actions: [edit, issue, source]
  open-graph: true
  site-url: "https://github.com/laurenchenarides/csu-arec-310"
  google-analytics:
    tracking-id: "G-GG4GM3TPXK"
    anonymize-ip: false

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true

execute: 
  freeze: auto

comments:
  hypothesis: false
  

