---
title: Homework 4
#description-meta: "{{<br meta website.description >}}"
#draft: true
format: 
  html: 
    theme: cosmo
 #   css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
---

Homework 4 is an excerpt from [the project instructions](project-instructions.qmd), specifically Email 3, and covers material related to the recent modules we’ve covered. You can work alone or in your Project Teams, but **everyone must hand in their own assignment**. 

## Instructions

Management is interested in understanding the competitive landscape of the Colorado retail milk market. They want to assess the level of market concentration and determine if the market structure resembles perfect competition or tends towards oligopoly. To achieve this, you are asked to calculate and analyze key market structure indicators. These calculations will help determine Cousins' position in the market relative to its competitors and provide insights into the overall market dynamics.

Management wants to understand the position of the firm in the market. They ask you to perform the following calculations and report back in one, easy-to-understand email:

1. Calculate the HHI of the market and graph it over time. Discuss your findings. 
2. Calculate the CR4 and the CR2 and graph each over time. Discuss your findings. 
3. Based on these findings, can we assume the market is behaving as if it is perfectly competitive? Describe your rationale in your email.

**Submission Notes:**

- You must create a new `date` variable by combining the `month` and `year` variables using an Excel formula.
- Each graph should be formatted to appear on their own worksheet. Points will be deducted for graphs that are embedded on the data sheet itself.
- Your email should be clear, concise, and actionable, providing management with the information they need to make informed decisions about Cousins' pricing strategies in the Colorado retail milk market.



