## Academic Integrity

Academic misconduct (see examples below) undermines the educational experience at Colorado State University, lowers morale by engendering a skeptical attitude about the quality of education, and negatively affects the relationship between students and faculty/instructors.

Faculty/Instructors are expected to use reasonably practical means of preventing and detecting academic misconduct. Any student found responsible for having engaged in academic misconduct will be subject to academic penalty and/or University disciplinary action.

Students are encouraged to positively impact the academic integrity culture of CSU by reporting incidents of academic misconduct.

Examples of academic misconduct include (but are not limited to):

1. Cheating – Cheating includes using unauthorized sources of information and providing or receiving unauthorized assistance on any form of academic work or engaging in any behavior specifically prohibited by the instructor in the course syllabus or class presentation. 

2. Plagiarism – Plagiarism includes the copying of language, structure, images, ideas, or thoughts of another, and representing them as one’s own without proper acknowledgment, and is related only to work submitted for credit. Also included is the failure to cite sources properly; sources must always be appropriately referenced, whether the source is printed, electronic or spoken.

3. Unauthorized Possession or Disposition of Academic Materials – Unauthorized possession or disposition of academic materials includes the unauthorized selling or purchasing of examinations, term papers, or other academic work; stealing another student’s work; and using information from or possessing exams that an instructor did not authorize for release to students.

4. Falsification – Falsification encompasses any untruth, either verbal or written, in one’s academic work.

5. Facilitation of any act of Academic Misconduct – Facilitation of any act of academic misconduct includes knowingly assisting another to commit an act of misconduct.

### Policy on Use of Generative AI

You may use generative AI tools (e.g., ChatGPT) as a research assistant to help you solve problems and to help you understand the concepts used in this course. However, if you choose to use such tools, you are claiming the resulting work as your own, and you bear full responsibility for its accuracy and appropriateness. In your assignments, **you must disclose if AI tools were used and how**. Doing so may not harm your grade; rather, it helps me guide you in using these tools effectively to enhance your grasp of the material. Remember, generative AI cannot advocate for itself or provide proper attributions; it is your responsibility to ensure integrity in your work.
