## Principles of Community

The Principles of Community support the Colorado State University mission and vision of access, research, teaching, service and engagement. A collaborative, and vibrant community is a foundation for learning, critical inquiry, and discovery. Therefore, each member of the CSU community has a responsibility to uphold these principles when engaging with one another and acting on behalf of the University

*Inclusion*: We create and nurture inclusive environments and welcome, value and affirm all members of our community, including their various identities, skills, ideas, talents, and contributions.

*Integrity*: We are accountable for our actions and will act ethically and honestly in all our interactions.

*Respect*: We honor the inherent dignity of all people within an environment where we are committed to freedom of expression, critical discourse, and the advancement of knowledge.

*Service*: We are responsible, individually and collectively, to give of our time, talents, and resources to promote the well-being of each other and the development of our local, regional, and global communities.

*Social Justice*: We have the right to be treated and the responsibility to treat others with fairness and equity, the duty to challenge prejudice, and to uphold the laws, policies and procedures that promote justice in all respects.