## Mental Health Statement

### Need Help?

CSU is a community that cares for you. If you are struggling with drugs or alcohol and/or experiencing depression, anxiety, overwhelming stress or thoughts of hurting yourself or others please know there is help available. Counseling Services has trained professionals who can help. Contact 970.491.6053 or go to http://health.colostate.edu. If you are concerned about a friend or peer, tell someone at by calling 970.491.1350 to discuss your concerns with a professional who can discreetly connect the distressed individual with the proper resources (http://supportandsafety.colostate.edu/tellsomeone). Rams take care of Rams. Reach out and ask for help if you or someone you know is having a difficult time.

### Sexual Assault and Violence Elimination

CSU’s Student Sexual Harassment and Violence policy, following national guidance from the Office of Civil Rights, requires that professors follow CSU policy as a “mandatory reporter” of any personal disclosure of sexual harassment, abuse, and/or violence related experiences or incidents shared with the professor in person, via email, and/or in classroom papers or homework exercises. These disclosures include but are not limited to reports of personal relational abuse, relational/domestic violence, and stalking. While professors are often able to help students locate appropriate channels of assistance on campus (e.g., see the CSU Health Network link below), disclosure by the student to the professor requires that the professor inform appropriate CSU channels to help ensure that the student’s safety and welfare is being addressed, even if the student requests that the disclosure not be shared.

For counseling support and assistance, please see The CSU HEALTH NETWORK, which includes a variety of counseling services that can be accessed at: [http://www.health.colostate.edu/](http://www.health.colostate.edu/). And, The Sexual Assault Victim Assistance Team is a confidential resource for students that does not have a reporting requirement and that can be of great help to students who have experienced sexual assault. The web address is [http://www.wgac.colostate.edu/need-help-support](http://www.wgac.colostate.edu/need-help-support).