---
title: The Case Method
format: 
  html: 
    theme: cosmo
 #   css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

## Why Case Studies?

What’s the most efficient way to learn? **From experience.**

Case studies give you the **benefits of learning from experience—without having to live through it yourself**. You’ll get to analyze real decisions, real dilemmas, and real tradeoffs that entrepreneurs face, and use them to sharpen your own thinking.

Each case is an opportunity to build a **deeper well of experience** you can draw from in your own entrepreneurial journey.


## The HBS Case Method Defined

Want to understand what makes a case discussion so different? This short video from Harvard Business School introduces the method behind the world’s most famous case classrooms. Watch to see how it works and why it's been used by entrepreneurs, leaders, and changemakers for over 100 years.

<iframe width="560" height="315" src="https://www.youtube.com/embed/h80hmEAGBbM?si=4oCPlv7kuS_at3Z4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


## Take a Seat in the Classroom

Curious what a real case discussion looks and feels like? This clip takes you inside the classroom so you can hear how students engage with a real case, voice different perspectives, and build on each other's thinking.

<iframe width="560" height="315" src="https://www.youtube.com/embed/p7iwXvBnbIE?si=u1iknKKSd3_Rjv4f" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
